### ISSUE TITLE
Angular 16 Upgrade Issues

### ISSUE THREAD

**Issue by lukestanley** [kendraio/kendraio-app#440]
- [x] #441
  - [x] Find if AG Grid broken in this branch #445 
  - [x] Material UI: different spacing and font style #446 
  - [x] Card component has broken UI  #446
  - [x] "Add Task" modal has different UI #446 
- [x] /connet page last link text font style and size #446
- [x] Review tests, are force clicks needed with new Cypress version? https://github.com/kendraio/kendraio-app/pull/457
- [x] Undo "Workflow" text to "Flow" - regression #448 
- [/] In Flow Cloud, flows don't show up at first render - This part it will be taken care of by the improvement on the reactivity of the whole app. To see PRs that deal with this, look for issues and PR with `state` label

**Comment by lukestanley** [comment]
This was made as part of a test, see comment on #441.

**Comment by gsambrotta** [comment]
This is probably the cause of most of our UI related issues: https://material.angular.io/guide/mdc-migration

**Comment by gsambrotta** [comment]
All the issue listed in this Issue have been merged, so I am closing this issue
